/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 23 17:18:31 GMT 2026
 *
 * EvoSuite settings: DYNAMOSA, seed=1, criterion=BRANCH, search_budget=60
 * Branch coverage: 93%, 21 tests generated
 */

package ee.ut.cs.swt.nextdate;

import static org.junit.Assert.*;
import org.junit.Test;

public class GTv1 {

    @Test
    public void test00() {
        NextDate nextDate0 = new NextDate(9, 9, 9);
        assertEquals("9/10/1826", nextDate0.run(9, 9, 1826));
    }

    @Test
    public void test01() {
        NextDate nextDate0 = new NextDate(8, 8, 8);
        assertEquals("8/9/1826", nextDate0.run(8, 8, 1826));
    }

    @Test
    public void test02() {
        NextDate nextDate0 = new NextDate(3, 3, 3);
        assertEquals("3/4/1810", nextDate0.run(3, 3, 1810));
    }

    @Test
    public void test03() {
        NextDate nextDate0 = new NextDate(1, 1, 1);
        assertEquals("1/2/1835", nextDate0.run(1, 1, 1835));
    }

    @Test
    public void test04() {
        NextDate nextDate0 = new NextDate(2, 2, 2);
        assertEquals("Invalid Input Date", nextDate0.run(2, 29, 1819));
    }

    @Test
    public void test05() {
        NextDate nextDate0 = new NextDate(2, 2, 2);
        assertEquals("3/1/1879", nextDate0.run(2, 28, 1879));
    }

    @Test
    public void test06() {
        NextDate nextDate0 = new NextDate(2, 2, 2);
        assertEquals("2/3/1819", nextDate0.run(2, 2, 1819));
    }

    @Test
    public void test07() {
        NextDate nextDate0 = new NextDate(7, 7, 7);
        assertEquals("7/31/1930", nextDate0.run(7, 31, 1930));
    }

    @Test
    public void test08() {
        NextDate nextDate0 = new NextDate(12, 12, 12);
        assertEquals("12/13/1839", nextDate0.run(12, 12, 1839));
    }

    @Test
    public void test09() {
        NextDate nextDate0 = new NextDate(4, 4, 4);
        assertEquals("5/1/1808", nextDate0.run(4, 30, 1808));
    }

    @Test
    public void test10() {
        NextDate nextDate0 = new NextDate(6, 6, 6);
        assertEquals("6/12/1886", nextDate0.run(6, 11, 1886));
    }

    @Test
    public void test11() {
        NextDate nextDate0 = new NextDate(11, 11, 11);
        assertEquals("Invalid Input Date", nextDate0.run(11, 31, 1858));
    }

    @Test
    public void test12() {
        NextDate nextDate0 = new NextDate(12, 12, 12);
        assertEquals("5/4/1880", nextDate0.run(5, 3, 1880));
    }

    @Test
    public void test13() {
        NextDate nextDate0 = new NextDate(10, 10, 10);
        assertEquals("11/1/1819", nextDate0.run(10, 31, 1819));
    }

    @Test
    public void test14() {
        NextDate nextDate0 = new NextDate(12, 12, 12);
        assertEquals("invalid Input Date", nextDate0.run(12, 1839, 1839));
    }

    @Test
    public void test15() {
        NextDate nextDate0 = new NextDate(1, 1, 1);
        assertEquals("invalid Input Date", nextDate0.run(1, 1, 2022));
    }

    @Test
    public void test16() {
        NextDate nextDate0 = new NextDate(4, 4, 4);
        assertEquals("invalid Input Date", nextDate0.run(4, 4, 4));
    }

    @Test
    public void test17() {
        NextDate nextDate0 = new NextDate(12, 12, 12);
        assertEquals("invalid Input Date", nextDate0.run(1880, 1880, 12));
    }

    @Test
    public void test18() {
        NextDate nextDate0 = new NextDate(12, 12, 12);
        assertEquals("invalid Input Date", nextDate0.run((-441), 12, (-441)));
    }

    @Test
    public void test19() {
        NextDate nextDate0 = new NextDate(2, 2, 2);
        assertEquals("Invalid Input Date", nextDate0.run(2, 31, 1901));
    }

    @Test
    public void test20() {
        NextDate nextDate0 = new NextDate(2, 2, 2);
        assertEquals("invalid Input Date", nextDate0.run(0, (-275), (-1198)));
    }
}
