/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 23 GMT 2026
 *
 * EvoSuite settings: DYNAMOSA, seed=1, criterion=BRANCH, search_budget=60
 * Generated for NDv12 (Faults 1 and 2 fixed, Fault 3 remains, no leap year)
 * Branch coverage: 97%, 22 tests generated
 */

package ee.ut.cs.swt.nextdate;

import static org.junit.Assert.*;
import org.junit.Test;

public class GTv12 {

    @Test
    public void test00() {
        NextDate nextDate0 = new NextDate((-285), 1, 1);
        assertEquals("6/2/2021", nextDate0.run(6, 1, 2021));
    }

    @Test
    public void test01() {
        NextDate nextDate0 = new NextDate((-194), (-194), 2021);
        assertEquals("4/5/2021", nextDate0.run(4, 4, 2021));
    }

    @Test
    public void test02() {
        NextDate nextDate0 = new NextDate(1963, 1963, 985);
        assertEquals("5/6/1963", nextDate0.run(5, 5, 1963));
    }

    @Test
    public void test03() {
        NextDate nextDate0 = new NextDate(3, 3, 3);
        assertEquals("3/4/1801", nextDate0.run(3, 3, 1801));
    }

    @Test
    public void test04() {
        NextDate nextDate0 = new NextDate((-8), (-8), (-8));
        assertEquals("1/13/1957", nextDate0.run(1, 12, 1957));
    }

    @Test
    public void test05() {
        NextDate nextDate0 = new NextDate(1970, 1970, 1970);
        assertEquals("Invalid Input Date", nextDate0.run(2, 29, 1970));
    }

    @Test
    public void test06() {
        NextDate nextDate0 = new NextDate((-395), (-395), 5);
        assertEquals("3/1/1909", nextDate0.run(2, 28, 1909));
    }

    @Test
    public void test07() {
        NextDate nextDate0 = new NextDate(1963, 1963, 1963);
        assertEquals("2/3/1963", nextDate0.run(2, 2, 1963));
    }

    @Test
    public void test08() {
        NextDate nextDate0 = new NextDate(1970, 1970, 1970);
        assertEquals("7/17/1970", nextDate0.run(7, 17, 1970));
    }

    @Test
    public void test09() {
        NextDate nextDate0 = new NextDate(14, 14, 14);
        assertEquals("12/15/2019", nextDate0.run(12, 14, 2019));
    }

    @Test
    public void test10() {
        NextDate nextDate0 = new NextDate(14, 14, 14);
        assertEquals("1/1/2020", nextDate0.run(12, 31, 2019));
    }

    @Test
    public void test11() {
        NextDate nextDate0 = new NextDate(30, 30, 30);
        assertEquals("10/1/1991", nextDate0.run(9, 30, 1991));
    }

    @Test
    public void test12() {
        NextDate nextDate0 = new NextDate(14, 14, 14);
        assertEquals("Invalid Input Date", nextDate0.run(11, 31, 2019));
    }

    @Test
    public void test13() {
        NextDate nextDate0 = new NextDate(1940, 1940, 1940);
        assertEquals("9/1/1940", nextDate0.run(8, 31, 1940));
    }

    @Test
    public void test14() {
        NextDate nextDate0 = new NextDate(10, 10, 1801);
        assertEquals("10/11/1801", nextDate0.run(10, 10, 1801));
    }

    @Test
    public void test15() {
        NextDate nextDate0 = new NextDate(1970, 1970, 1970);
        assertEquals("invalid Input Date", nextDate0.run(2, 1970, 1970));
    }

    @Test
    public void test16() {
        NextDate nextDate0 = new NextDate(3718, 3718, 3718);
        assertEquals("invalid Input Date", nextDate0.run(12, 3718, 3718));
    }

    @Test
    public void test17() {
        NextDate nextDate0 = new NextDate(1, 1, 1);
        assertEquals("invalid Input Date", nextDate0.run(1, 1, 1));
    }

    @Test
    public void test18() {
        NextDate nextDate0 = new NextDate(21, 21, 21);
        assertEquals("invalid Input Date", nextDate0.run(21, 21, 21));
    }

    @Test
    public void test19() {
        NextDate nextDate0 = new NextDate(0, 0, 0);
        assertEquals("invalid Input Date", nextDate0.run(0, 1089, 1089));
    }

    @Test
    public void test20() {
        NextDate nextDate0 = new NextDate(0, 0, 0);
        assertEquals("invalid Input Date", nextDate0.run(0, 0, 0));
    }

    @Test
    public void test21() {
        NextDate nextDate0 = new NextDate(1959, 1959, 1959);
        assertEquals("Invalid Input Date", nextDate0.run(2, 31, 1959));
    }
}
