/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 23 GMT 2026
 *
 * EvoSuite settings: DYNAMOSA, seed=1, criterion=BRANCH, search_budget=60
 * Generated for NDv2 (Faults 1 and 2 fixed, Fault 3 remains, leap year enabled)
 * Branch coverage: 92%, 23 tests generated
 */

package ee.ut.cs.swt.nextdate;

import static org.junit.Assert.*;
import org.junit.Test;

public class GTv2 {

    @Test
    public void test00() {
        NextDate nd = new NextDate(9, 9, 9);
        assertEquals("9/10/1862", nd.run(9, 9, 1862));
    }

    @Test
    public void test01() {
        NextDate nd = new NextDate(11, 11, 11);
        assertEquals("4/12/1879", nd.run(4, 11, 1879));
    }

    @Test
    public void test02() {
        NextDate nd = new NextDate(1, 1, 1);
        assertEquals("10/2/1879", nd.run(10, 1, 1879));
    }

    @Test
    public void test03() {
        NextDate nd = new NextDate((-3), (-3), (-3));
        assertEquals("5/31/1843", nd.run(5, 30, 1843));
    }

    @Test
    public void test04() {
        NextDate nd = new NextDate(9, 9, 9);
        assertEquals("3/4/1862", nd.run(3, 3, 1862));
    }

    @Test
    public void test05() {
        NextDate nd = new NextDate(11, 11, 11);
        assertEquals("Invalid Input Date", nd.run(2, 29, 1857));
    }

    @Test
    public void test06() {
        NextDate nd = new NextDate(11, 11, 11);
        assertEquals("Invalid Input Date", nd.run(2, 30, 1879));
    }

    @Test
    public void test07() {
        NextDate nd = new NextDate(55, 55, 55);
        assertEquals("3/1/1836", nd.run(2, 29, 1836));
    }

    @Test
    public void test08() {
        NextDate nd = new NextDate(2021, 2021, 2021);
        assertEquals("2/3/1862", nd.run(2, 2, 1862));
    }

    @Test
    public void test09() {
        NextDate nd = new NextDate(1, 1, 1);
        assertEquals("7/7/1823", nd.run(7, 7, 1823));
    }

    @Test
    public void test10() {
        NextDate nd = new NextDate(1, 1, 1);
        assertEquals("12/2/1961", nd.run(12, 1, 1961));
    }

    @Test
    public void test11() {
        NextDate nd = new NextDate(1, 1, 1);
        assertEquals("1/1/1962", nd.run(12, 31, 1961));
    }

    @Test
    public void test12() {
        NextDate nd = new NextDate(11, 11, 11);
        assertEquals("12/1/1879", nd.run(11, 30, 1879));
    }

    @Test
    public void test13() {
        NextDate nd = new NextDate(825, 825, 825);
        assertEquals("Invalid Input Date", nd.run(6, 31, 1977));
    }

    @Test
    public void test14() {
        NextDate nd = new NextDate(1, 1, 1);
        assertEquals("2/1/1977", nd.run(1, 31, 1977));
    }

    @Test
    public void test15() {
        NextDate nd = new NextDate(11, 11, 11);
        assertEquals("8/9/1879", nd.run(8, 8, 1879));
    }

    @Test
    public void test16() {
        NextDate nd = new NextDate(1, 1, 1);
        assertEquals("invalid Input Date", nd.run(1, 1823, 1823));
    }

    @Test
    public void test17() {
        NextDate nd = new NextDate(11, 11, 11);
        assertEquals("invalid Input Date", nd.run(9, 2, 3229));
    }

    @Test
    public void test18() {
        NextDate nd = new NextDate(49, 49, 49);
        assertEquals("3/1/2021", nd.run(2, 28, 2021));
    }

    @Test
    public void test19() {
        NextDate nd = new NextDate(1, 1, 1);
        assertEquals("invalid Input Date", nd.run(1823, 1759, 1759));
    }

    @Test
    public void test20() {
        NextDate nd = new NextDate(1, 1, 1);
        assertEquals("invalid Input Date", nd.run((-3335), 1977, (-3335)));
    }

    @Test
    public void test21() {
        NextDate nd = new NextDate(11, 11, 11);
        assertEquals("invalid Input Date", nd.run(11, (-4593), 1364));
    }

    @Test
    public void test22() {
        NextDate nd = new NextDate(49, 49, 49);
        assertEquals("invalid Input Date", nd.run(2, 2, 49));
    }
}
